name: Build CV PDFs

on:
  push:
    branches:
      - master
    paths:
      - 'app/data/**'
      - 'app/templates/**'
      - 'app/build-cv.sh'
      - '.github/workflows/build-pdf.yaml'
  pull_request:
    branches:
      - master
    paths:
      - 'app/data/**'
      - 'app/templates/**'
      - 'app/build-cv.sh'
      - '.github/workflows/build-pdf.yaml'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug changed files
        run: |
          echo "Changed files in this commit:"
          git diff --name-only HEAD^ HEAD || echo "No diff available (first commit?)"

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag cv-builder:${{ github.sha }}

      - name: Run English CV build in Docker
        run: |
          docker run --rm -v $(pwd)/app:/app cv-builder:${{ github.sha }} bash /app/build-cv.sh --lang en

      - name: Run Spanish CV build in Docker
        run: |
          docker run --rm -v $(pwd)/app:/app cv-builder:${{ github.sha }} bash /app/build-cv.sh --lang es

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: generated-cvs
          path: |
            app/output/cv-en.pdf
            app/output/cv-es.pdf
          retention-days: 2
